plugins {
    id 'java'
}

group = 'dev.plytki'
version = '2.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(path: ':base-commands')
    implementation project(path: ':base-inventories')
    implementation project(path: ':base-plugin')
    implementation project(path: ':base-redis')

    compileOnly 'org.redisson:redisson:3.16.4' // Redisson
    compileOnly 'org.msgpack:jackson-dataformat-msgpack:0.9.3' // Redisson Codec
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.filter { it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

processResources {
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand projectVersion: project.version
    }
}