plugins {
    id 'java'
    id 'maven-publish'
}

group = 'dev.plytki'
version = '2.0.0-SNAPSHOT'

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = 'base-api'
            version = version
            from components.java
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/plytki/base-api"
            credentials {
                username = System.getenv("USERNAME")
                password = System.getenv("TOKEN")
            }
        }
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.filter { it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

processResources {
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand projectVersion: project.version
    }
}

subprojects {

    apply plugin: 'java'
    apply plugin: 'maven-publish'

    repositories {
        mavenCentral()
        maven { url = 'https://jitpack.io' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://oss.sonatype.org/content/groups/public/' }
    }

    dependencies {
        compileOnly 'io.papermc.paper:paper-api:1.19.3-R0.1-SNAPSHOT'
        compileOnly 'com.mojang:authlib:1.5.25'
        compileOnly 'org.jetbrains:annotations:24.0.1'
        compileOnly 'org.projectlombok:lombok:1.18.26'

        annotationProcessor "org.projectlombok:lombok:1.18.26"
        annotationProcessor "org.jetbrains:annotations:23.1.0"

        testImplementation platform('org.junit:junit-bom:5.9.1')
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(17))
    }

    compileJava.options.encoding = 'UTF-8'
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    test {
        useJUnitPlatform()
    }

}
