plugins {
    id 'java'
    id 'maven-publish'
}

group = 'dev.plytki'
version = rootProject.version

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = 'base-redis'
            version = version
            from components.java
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/plytki/base-api"
            credentials {
                username = System.getenv("USERNAME")
                password = System.getenv("TOKEN")
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.redisson:redisson:3.25.2'
    implementation 'org.msgpack:jackson-dataformat-msgpack:0.9.3'
    implementation 'com.google.code.gson:gson:2.10.1'
}