plugins {
    id 'java'
}

group = 'dev.plytki'
version = rootProject.version

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = 'base-commands'
            version = version
            from components.java
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/plytki/base-api"
            credentials {
                username = System.getenv("USERNAME")
                password = System.getenv("TOKEN")
            }
        }
    }
}

repositories {
    mavenCentral()
}