plugins {
    id 'java'
}

group = 'dev.plytki'
version = '2.0.1-SNAPSHOT'

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = 'base-plugin'
            version = version
            from components.java
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/plytki/base-api"
            credentials {
                username = System.getenv("USERNAME")
                password = System.getenv("TOKEN")
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(path: ':base-commands')
    implementation project(path: ':base-inventories')
    implementation project(path: ':base-redis')

    compileOnly 'org.redisson:redisson:3.16.4' // Redisson
    compileOnly 'org.msgpack:jackson-dataformat-msgpack:0.9.3' // Redisson Codec
}